language: c

compiler:
  - gcc
  - clang

install: true
arch:
  - ppc64le 
  - amd64 
  
branches:
  except:
    - 5.9.6

before_script:
  - autoreconf -fi

script:
  - ./configure && make && make all-test
